version: '3.8'

services:
  backend:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
    environment:
      - API_BASE_URL=http://localhost:8000
      - ENVIRONMENT=development
    volumes:
      - .:/app
      - ./storage:/app/storage
      - ./output:/app/output
    depends_on:
      - redis
    command: poetry run uvicorn backend.api.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      target: development
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://backend:8000
    volumes:
      - .:/app
    depends_on:
      - backend
    command: poetry run streamlit run frontend/app.py --server.port 8501 --server.address 0.0.0.0

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Optional: Database service (if you want to use PostgreSQL instead of SQLite)
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: ai_nvcb
  #     POSTGRES_USER: ai_nvcb
  #     POSTGRES_PASSWORD: ai_nvcb_password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  # postgres_data:
